### PR TITLE
Mention trim and trim_in_place operations

### PR DESCRIPTION
**Pull request by Theodus**
This is the final part of [RFC #4](https://github.com/ponylang/rfcs/blob/master/text/0004-string-array-trim.md) to be implemented.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
I dont think this works Theo. I read this and I'm now left confused.

Everything still only addresses append but there's been some other content that feels thrown in. Perhaps usage of trim and trim in place should be a different pattern?

I'm thinking that would be better and more understandable.

**Comment by Theodus** [comment]
@SeanTAllen I'm not sure if it should be another pattern because, as I understand it, the `trim` and `trim_in_place` methods are meant to improve performance by reducing string allocations. I'll see if I can add more detail so that it doesn't seem so thrown in.

**Comment by SeanTAllen** [comment]
@Theodus well, its solving two different problems.

1 is related to concatentation
the other is related to substring

and they have different solutions and different discussion points.

I think it is reasonable to have 2 patterns, one for each. We might need to consider a bit of renaming.

Awful first idea:

"Limiting String Allocations: Append"
"Limiting String Allocations: ???"

Ok, just looking at it, that's awful.

I think we should have 2 patterns, with good names for each.

**Comment by Theodus** [comment]
@SeanTAllen Is it possible that this doesn't belong in a pattern, but instead should be included in the documentation for `String.substring`? For example the method docstring could be extended like so:
```pony
fun substring(from: ISize, to: ISize = ISize.max_value()): String iso^ =>
  """
  Returns a substring. Index range [`from` .. `to`) is half-open.
  Returns an empty string if nothing is in the range.

  Note that this operation allocates a new string to be returned. For
  similar operations that don't allocate a new string, see `trim` and
  `trim_in_place`.
  """
```

**Comment by SeanTAllen** [comment]
I think that is an excellent idea. 

I think there could still be a pattern about the general usage of trim and trim in place. But having that in the method for substring etc is a very good idea.

**Comment by SeanTAllen** [comment]
But you are right, maybe it isn't a pattern.

**Comment by SeanTAllen** [comment]
I'm willing to say "not a pattern"

**Comment by Theodus** [comment]
I've opened a PR to do that then: https://github.com/ponylang/ponyc/pull/1815

**Pull request closed without merging**
