### PR TITLE
Clean up and clarify the Notifier Interaction example

### PR DESCRIPTION
**Pull request by krig**
The example didn't clearly demonstrate structural typing
since it explictly declared TestNotifier as implementing
Notified. It also needlessly passed the Receiver along
to the received method, even though it was never used.

This commit clarifies the use of structural typing, and
reduces the signature of received to just the message.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
Hi @krig,

Thanks for the attempt. However, I don't agree with these changes and they obscure a very common and important purpose with a notifier. 

The removal of "this" defeats most of the purpose of a notifier. Without the "this" being passed, you can't exercise any control. 

Closing.

**Comment by krig** [comment]
Hi Sean!

No problem, I understand. I was confused since this was never used in the notifier, so I didn’t quite get why it was passed along.

What about just removing the interface usage (is TestNotifier)? That part also confused me a bit as a newbie, I had to go and try removing it to see if I had misunderstood something about interfaces. So mainly I wanted to clarify that point.

**Comment by SeanTAllen** [comment]
you can use `is Interface`.

Its not required. It's rather common in  Pony code to see the `is Blah` as it helps indicate "this is a Blah". And to indicate a specific purpose.

**Comment by krig** [comment]
I see, yeah. So unlike Go where declaring `is Blah` it's not even an option, here you can optionally declare the implementation, and stylistically that's preferred when possible. Makes sense.

**Comment by jemc** [comment]
> stylistically that's preferred when possible

It also has the benefit of acting like an assertion of sorts, so that you'll be issued the correct compile-time error if the interface ever diverges from your implementation. If I tell the compiler `class Class is Interface`, I'll be notified by the compiler if that statement ever becomes not-true.

**Pull request closed without merging**
